version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: multitenant_fastapi_engine
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped